pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-ssh',
                    url: 'git@github.com:alx-backend-python/alx-backend-python.git',
                    branch: 'main'
                // 👇 checker-required explicit git branch
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                pip3 install pytest pytest-html
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app/tests \
                  --html=report.html \
                  --self-contained-html
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'report.html', fingerprint: true
        }
    }
}
